testing one more time

diff --git a/.github/workflows/update-durations.yml b/.github/workflows/update-durations.yml
--- a/.github/workflows/update-durations.yml
+++ b/.github/workflows/update-durations.yml
@@ -61,9 +61,9 @@ jobs:
       - name: Stage changes
         # if: steps.changed.outputs.has_changes != '0'
         run: |
-          echo "Blseah" >> .github/durations/tf_tests_durations.json
-          echo "Blesah" >> .github/durations/jax_tests_durations.json
-          echo "Blesah" >> .github/durations/core_tests_durations.json
+          echo "Blh" >> .github/durations/tf_tests_durations.json
+          echo "Bah" >> .github/durations/jax_tests_durations.json
+          echo "ah" >> .github/durations/core_tests_durations.json
           git add .github/durations/
           git commit -m "Update durations files"
           git push -f --set-upstream origin "${{ env.DURATIONS_BRANCH }}"
@@ -75,12 +75,15 @@ jobs:
           GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
           PR_REVIEWER: PennyLaneAI/core
           PR_TITLE: "Update test duration files"
-          PR_BODY: |
-            Automatic update of test duration files.
-
-            Because bots are not able to trigger CI on their own, please do so by pushing an empty commit to this branch.
-
-            Alternatively, wait for this branch to be out-of-date with master, then just use the 'Update branch' button.
         run: |
-          gh_pr_up() { gh pr create "$@" --reviewer $PR_REVIEWER || { gh pr reopen $(git branch --show-current); gh pr edit "$@" --add-reviewer $PR_REVIEWER; } }
-          gh_pr_up --title $PR_TITLE --body $PR_BODY
+          gh_pr_up() {
+            # Create a new pull request with provided arguments
+            gh pr create --title $PR_TITLE --reviewer $PR_REVIEWER || {
+              # If PR creation fails, reopen the PR associated with the current branch
+              gh pr reopen $(git branch --show-current)
+              
+              # Edit the existing PR to add the reviewer
+              gh pr edit --title $PR_TITLE --add-reviewer $PR_REVIEWER
+            }
+          }
+          gh_pr_up
